wearesocial/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from accounts.views import register, login, profile, logout, subscriptions_webhook, paypal_cancel, paypal_return, \
    all_products
from paypal.standard.ipn import urls as paypal_urls
from products.views import magazines
import core.views
from threads.views import threads
import threads.views
import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', core.views.get_index, name='home'),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^contact/', 'contact.views.contact', name='contact'),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', login, name='login'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^//logout/$', logout, name='logout'),
    url(r'^accounts/subscriptions/$', subscriptions_webhook),
    url(r'^a-very-hard-to-guess-url/', include(paypal_urls)),
    url(r'^paypal-return/$', paypal_return),
    url(r'^paypal-cancel/$', paypal_cancel),
    url(r'^products/$', all_products, name="products"),
    url(r'^magazines/$', magazines, name="magazines"),

    url(r'^forum/$', threads.views.forum, name="forum"),
    url(r'^threads/(?P<subject_id>\d+)/$', threads.views.threads, name="threads"),
    url(r'^new_thread/(?P<subject_id>\d+)/$', threads.views.new_thread, name='new_thread'),
    url(r'^thread/(?P<thread_id>\d+)/$', threads.views.thread, name='thread'),
    url(r'^post/new/(?P<thread_id>\d+)/$', threads.views.new_post, name='new_post'),
    url(r'^post/edit/(?P<thread_id>\d+)/(?P<post_id>\d+)/$', threads.views.edit_post, name='edit_post'),
    url(r'^post/delete_post/(?P<post_id>\d+)/$', threads.views.delete_post, name='delete_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone


class ContactForm(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=250)
    topic = models.CharField(max_length=200)
    message = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.email

    class Meta:
        ordering = ['timestamp']

products/models.py
from paypal.standard.ipn.signals import subscription_signup, subscription_cancel
from django.contrib.auth.models import AbstractUser
import arrow


def subscription_created(sender, **kwargs):
    ipn_obj = sender

    magazine_id = ipn_obj.custom.split('-')[0]
    user_id = ipn_obj.custom.split('-')[1]

    purchase = Purchase.objects.create(magazine_id=magazine_id,
                                       user_id=user_id,
                                       subscription_end=arrow.now().replace(weeks=+ 4).datetime)


subscription_signup.connect(subscription_created)


def subscription_was_cancelled(sender, **kwargs):
    ipn_obj = sender

    magazine_id = ipn_obj.custom.split('-')[0]
    user_id = ipn_obj.custom.split('-')[1]

    purchase = Purchase.objects.get(user_id=user_id, magazine_id=magazine_id)
    purchase.subscription_end = arrow.now()
    purchase.save()


subscription_cancel.connect(subscription_was_cancelled)

threads/models.py
from django.db import models
from tinymce.models import HTMLField
from django.conf import settings
from django.utils import timezone


class Subject(models.Model):
    name = models.CharField(max_length=254)
    description = HTMLField()

    def __unicode__(self):
        return self.name


class Thread(models.Model):
    name = models.CharField(max_length=254)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='threads')
    subject = models.ForeignKey(Subject, related_name='threads')
    created_at = models.DateTimeField(default=timezone.now)


class Posts(models.Model):
    thread = models.ForeignKey(Thread, related_name='posts')
    comment = HTMLField(blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts')
    created_at = models.DateTimeField(default=timezone.now)


class Poll(models.Model):
    question = models.TextField()
    thread = models.OneToOneField(Thread, null=True)


class PollSubject(models.Model):
    name = models.CharField(max_length=256)
    poll = models.ForeignKey(Poll, related_name='subjects')


class Vote(models.Model):
    poll = models.ForeignKey(Poll, related_name="votes")
    subject = models.ForeignKey(PollSubject, related_name="votes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="votes")

contact/forms.py
from django.forms import ModelForm
from .models import ContactForm
from django import forms


class ContactView(ModelForm):
    message = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ContactForm
        fields = ('name', 'email', 'topic', 'message')

threads/forms.py
from django import forms
from .models import Thread, Poll, PollSubject, Posts


class ThreadForm(forms.ModelForm):
    name = forms.CharField(label="Thread name")
    is_a_poll = forms.BooleanField(label="Include a poll?", required=False)

    class Meta:
        model = Thread
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['comment']


class PollForm(forms.ModelForm):
    question = forms.CharField(label="What is your poll about?")

    class Meta:
        model = Poll
        fields = ['question']


class PollSubjectForm(forms.ModelForm):
    name = forms.CharField(label="Poll subject name", required=True)

    def __init__(self, *args, **kwargs):
        super(PollSubjectForm, self).__init__(*args, **kwargs)

        self.empty_permitted = False

    class Meta:
        model = PollSubject
        fields = ['name']

contact/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import ContactView


def contact(request):
    if request.method == 'POST':
        form = ContactView(request.POST)
        if form.is_valid():
            our_form = form.save(commit=False)
            our_form.save()
            messages.add_message(request, messages.SUCCESS, 'Your message has been sent. Thank you.')
            return render(request, 'index.html')
    else:
        form = ContactView()
    return render(request, 'contact.html', {'form': form})

products/views.py
from django.shortcuts import render
from accounts.models import Magazine


def magazines(request):
    args = {'magazines': Magazine.objects.all()}
    return render(request, 'magazines.html', args)

threads/views.py
from django.shortcuts import render, get_object_or_404
from models import Subject, Thread, Posts, PollSubject
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.template.context_processors import csrf
import arrow
from django import template
from django.forms import formset_factory
from threads.forms import ThreadForm, PollForm, PollSubjectForm, PostForm


def forum(request):
    return render(request, 'forum.html', {'subjects': Subject.objects.all()})


def threads(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    return render(request, 'threads.html', {'subject': subject})


@login_required
def new_thread(request, subject_id):
    subject = get_object_or_404(Subject, pk=subject_id)
    poll_subject_formset = formset_factory(PollSubjectForm, extra=3)
    if request.method == "POST":
        thread_form = ThreadForm(request.POST)
        post_form = PostForm(request.POST)
        poll_form = PollForm(request.POST)
        poll_subject_formset = poll_subject_formset(request.POST)
        if thread_form.is_valid() and post_form.is_valid() and poll_form.is_valid() and poll_subject_formset.is_valid():
            thread = thread_form.save(False)
            thread.subject = subject
            thread.user = request.user
            thread.save()

            post = post_form.save(False)
            post.user = request.user
            post.thread = thread
            post.save()

            poll = poll_form.save(False)
            poll.thread = thread
            poll.save()

            for subject_form in poll_subject_formset:
                subject = subject_form.save(False)
                subject.poll = poll
                subject.save()

        messages.success(request, "You have created a new thread!")

        return redirect(reverse('thread', args={thread.pk}))

    else:
        thread_form = ThreadForm()
        post_form = PostForm(request.POST)
        poll_form = PollForm()
        poll_subject_formset = poll_subject_formset()

    args = {
        'thread_form': thread_form,
        'post_form': post_form,
        'subject': subject,
        'poll_form': poll_form,
        'poll_subject_formset': poll_subject_formset,
    }

    args.update(csrf(request))

    return render(request, 'thread_form.html', args)


def thread(request, thread_id):
    thread_ = get_object_or_404(Thread, pk=thread_id)
    args = {'thread': thread_}
    args.update(csrf(request))
    return render(request, 'thread.html', args)


@login_required
def new_post(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)

    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(False)
            post.thread = thread
            post.user = request.user
            post.save()

            messages.success(request, "Your post has been added to the thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm()

    args = {
        'form': form,
        'form_action': reverse('new_post', args={thread.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'post_form.html', args)


@login_required
def edit_post(request, thread_id, post_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    post = get_object_or_404(Posts, pk=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, "Your have updated your thread!")

            return redirect(reverse('thread', args={thread.pk}))
    else:
        form = PostForm(instance=post)

    args = {
        'form': form,
        'form_action': reverse('edit_post', kwargs={"thread_id": thread.id,
                                                    "post_id": post.id}),
        'button_text': 'Update Post'
    }
    args.update(csrf(request))

    return render(request, 'post_form.html', args)


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    thread_id = post.thread.id
    post.delete()

    messages.success(request, "Your post was deleted!")

    return redirect(reverse('thread', args={thread_id}))


register = template.Library()


@register.filter
def get_total_subject_posts(subject):
    total_posts = 0
    for thread in subject.threads.all():
        total_posts += thread.posts.count()

    return total_posts


@register.filter
def started_time(created_at):
    return arrow.get(created_at).humanize()


@register.simple_tag
def last_posted_user_name(thread):
    posts = thread.posts.all().order_by('created_at')
    return posts.first().user.username


@login_required
def thread_vote(request, thread_id, subject_id):
    thread = Thread.objects.get(id=thread_id)

    subject = thread.poll.votes.filter(user=request.user)

    if subject:
        messages.error(request, "You already voted on this! ... your not trying to cheat are you?")
        return redirect(reverse('thread', args={thread_id}))

    subject = PollSubject.objects.get(id=subject_id)

    subject.votes.create(poll=subject.poll, user=request.user)

    messages.success(request, "We've registered your vote!")

    return redirect(reverse('thread', args={thread_id}))


@register.simple_tag
def user_vote_button(thread, subject, user):
    vote = thread.poll.votes.filter(user_id=user.id).first()

    if not vote:
        if user.is_authenticated():
            link = """
            <div class="col-md-3 btn-vote">
            <a href="%s" class="btn btn-default btn-sm">
                Add my vote!
            </a>
            </div>""" % reverse('cast_vote', kwargs={'thread_id': thread.id, 'subject_id': subject.id})

            return link

    return ""

templates/base.html
{% load staticfiles %}
<!DOCTYPE html >
<html lang="en">

<head>
    <meta charset="utf8">
    <title>We Are Social</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href=" {% static "css/font-awesome-4.5.0/css/font-awesome.min.css" %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.6/cerulean/bootstrap.min.css">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
    {% block head_js %}{% endblock head_js %}
</head>

<body>
    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li><a href=" {% url 'home' %} ">Home</a></li>
            <li><a href="/pages/about">About</a></li>
            <li><a href=" {% url 'products' %} ">DVD's</a></li>
            <li><a href=" {% url 'forum' %} ">Fourm</a></li>
            <li><a href=" {% url 'register' %} "> Register </a></li>
            <li><a href=" {% url 'login' %} "> Log In </a></li>
            <li><a href=" {% url 'logout' %} "> Log Out </a></li>
            <li><a href=" {% url 'contact' %} ">Contact</a></li>
        </ul>
        <div id="logo-nav">
            <a href="#"><img src="/media/img/nav-logo.png" alt="logo"></a>
        </div>
    </div>
    <hr>

    {% if messages %}
        <div class="alert alert-success">
            <div class="messages">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        </div>
    {% endif %}

        {% block content %}
        {% endblock %}
    <hr>
   <!-- <div class="footer">
        <p>Copyright © 2999 <a href="http://www.mcnultyshane.com">Shane McNulty
        </a>. Made By Shane McNulty with Django </p>
    </div>-->
</div>
</body>

<!--script references -->

</html>

templates/comment_details.html
{% load thread_extras %}
<div class="details">
    <div class="col-md-6">
        <div class="pull-left">
            <time datetime=" {{ post.created_at }} ">
                Posted: {{ post.created_at|started_time }}
            </time>
        </div>
    </div>
    <div class="col-md-6">
        <div class="pull-right">
            {% if post.user == user or user.is_staff %}
                <a href=" {% url 'edit_post' thread.id post.id %}"><i class="fa fa-pencil-square-o"></i></a>
                <a href="{% url 'delete_post' post.id %} "><i class="fa fa-trash-o"></i></a>
            {% endif %}
        </div>
    </div>
    <div class="clearfix"></div>
</div>

templates/contact.html
{% extends "base.html" %}
{% block content %}
    <div class="ding">
    {% load bootstrap_tags %}
    <div class="container-narrow">

        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | as_bootstrap }}
            <button type="submit" class=" btn btn btn-primary">Submit</button>
        </form>
    </div>
    </div>
{% endblock %}

templates/forum.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
    {% load bootstrap_tags %}
    {% for subject in subjects %}
        <section class="subject">
            <h2><a href="{% url "threads" subject.id %}"> {{ subject.name }}</a></h2>
            <p>
                <a href="{% url "threads" subject.id %}">
                    {% autoescape off %}{{ subject.description }}{% endautoescape %}
                </a>
            </p>
            <table>
                <tr>
                    <th>THREADS</th>
                    <th>POSTS</th>
                </tr>
                <tr>
                    <td> {{ subject.threads.count }} </td>
                    <td> {{ subject|get_total_subject_posts }} </td>
                </tr>
            </table>
        </section>
    {% endfor %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

        <div class="background">
            <div id="logo">
                <a href="#"><img src="/media/img/logo.png" alt="logo"></a>
            </div>
            <p class="lead">The Squared Circle Mecca</p>
            <a class="btn btn-large btn-success" href="contact">Join Suplex City</a><br/>
        </div>
    <hr>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block content %}
    <div class="container-wide">
        <form role="form" method="post" action=" {% url 'login' %} ">
            <legend>Login</legend>
            {% csrf_token %}
            {{ form|as_bootstrap }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Login</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/magazines.html
{% extends "base.html" %}
{% load magazine_extras %}
{% block content %}

     <h1> What the fuck is going on!!!!</h1>

    {% for magazine in magazines %}
        <tr>
            <td> {{ magazine.name }} </td>
            <td> {{ magazine.description }} </td>
            <td> $ {{ magazine.price }} </td>
            <td> {% paypal_form_for magazine user %}</td>
        </tr>
    {% endfor %}
{% endblock %}

templates/paypal_cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>{{ post }}</p>
<p>{{ get }}</p>
</body>
</html>

templates/paypal_return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>{{ post }}</p>
<p>{{ get }}</p>
</body>
</html>

templates/post_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% block head_js %}
    <script type="text/javascript" src=" {% static 'js/tinymce/tinymce.min.js' %} "></script>
    <script type="text/javascript">
        tinyMCE.init({
            mode: "textareas",
            theme: "modern",
            plugins: "paste",
        });
    </script>
{% endblock %}
{% block content %}
    <section>
        <div class="col-md-9">
            <form method="post" action="{{ form_action }}">
                {% csrf_token %}
                {{ form|as_bootstrap }}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary"> {{ button_text }} </button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

templates/thread_extras.html
{% extends 'base.html' %}
{% block content %}
{% endblock %}

templates/thread_form.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load staticfiles %}
{% load thread_extras %}

{% block head_js %}
    <script type="text/javascript" src=" {% static 'js/tinymce/tinymce.min.js' %} "></script>
    <script type="application/javascript">
        tinyMCE.init({mode: "textareas", theme: 'modern', plugins: 'paste'})
    </script>
{% endblock %}


{% block content %}
    <section>
        <div class="col-md-9">
            <form method="post" action=" {% url 'new_thread' subject.id %} ">
                {% csrf_token %}
                <div class="form-group">
                    {{ thread_form|as_bootstrap }}
                    <hr>
                    {{ post_form|as_bootstrap }}
                </div>
                <div id="poll_form" class="form-group">
                    {{ poll_form|as_bootstrap }}
                    {{ poll_subject_formset.management_form }}
                    {% for poll_subject_form in poll_subject_formset %}
                        {{ poll_subject_form|as_bootstrap }}
                    {% endfor %}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn-primary">
                        Post New Thread
                    </button>
                </div>
            </form>
        </div>
        {% if thread.poll %}
            <div class="container">
                <div class="col-md-6">
                    <h2>Poll</h2>
                    <strong>{{ thread.poll.question }}</strong><br><br>

                    <p>Heres how the votes are so far:</p>
                    {% for subject in thread.poll.subjects.all %}
                        <div class="col-md-10">
                            <strong>{{ subject.name }}</strong>
                            <span class="pull-right">{{ subject|vote_percentage }}%</span>
                        </div>
                        {% user_vote_button thread subject thread.user %}
                        <div class="col-md-10">
                            <div class="progress">
                                <div class="progress-bar progress-bar-info" role="progressbar"
                                     aria-value=" {{ subject|vote_percentage }}"
                                     aria-valuemin="0"
                                     aria-valuemax="100"
                                     style=" width :{{ subject|vote_percentage }}%;">
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
    </section>
    <script type="text/javascript">
        $(function () {
            if (!$('#id_is_a_poll').is(':checked')) {
                $('#poll_form').hide();
            }

            $('#id_is_a_poll').click(function (el) {
                var poll_form = $('#poll_form');

                if (poll_form.is(":visible")) {
                    poll_form.hide();
                } else {
                    poll_form.show();
                }
            });
        });
    </script>
{% endblock %}

templates/thread_item.html
<section class="thread">
    <header>
        <table>
            <tr>
                <td>
                    <a href=" {% url 'thread' thread.id %} "><h4> {{ thread.name }} </h4><a>
                </td>
            </tr>
        </table>
    </header>
</section>

templates/threads.html
{% extends "base.html" %}
{% load thread_extras %}
{% block content %}
    <div class="row header">
        <div class="jumbotron"><h1> {{ subject.name }} </h1></div>
    </div>
    <div class="col-md-12">
        {% if user.is_authenticated %}
            <p>
                <a href=" {% url 'new_thread' subject.id %} " class="btn btn-primary"> New Thread </a>
            </p>
        {% endif %}
        {% for thread in subject.threads.all %}
            {% include "thread_item.html" %}
        {% endfor %}
    </div>
{% endblock %}